apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Murkiness-Recapture-Subarctic3"
  MYSQL_PASSWORD: "Murkiness-Recapture-Subarctic3"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"